import type React from "react";

// EL5 MediProcure — Classic ERP Design System
export const ERP = {
  titleBar: "linear-gradient(180deg, #2a4fa3 0%, #1a3580 100%)",
  titleBarBorder: "#1a3580",
  titleText: "#ffffff",
  toolbar: "linear-gradient(180deg, #f0f0f0 0%, #dcdcdc 100%)",
  toolbarBorder: "#a0a0a0",
  statBg: "#ffffff",
  statBorder: "#cccccc",
  statValue: "#1a1a1a",
  statLabel: "#555555",
  statIcon: "#c0392b",
  sidebarBg: "#f5f5f5",
  sidebarBorder: "#cccccc",
  sidebarHeader: "linear-gradient(180deg,#2a4fa3,#1a3580)",
  sidebarHeaderText: "#ffffff",
  sidebarItem: "#333333",
  sidebarHover: "#dce9ff",
  sidebarActive: "#c5d9f1",
  gridHeader: "linear-gradient(180deg,#f0f0f0,#dcdcdc)",
  gridHeaderText: "#1a1a1a",
  gridHeaderBorder: "#a0a0a0",
  gridRow: "#ffffff",
  gridRowAlt: "#f7f7f7",
  gridRowHover: "#dce9ff",
  gridBorder: "#d0d0d0",
  gridText: "#1a1a1a",
  gridTextMuted: "#555555",
  btnPrimary: "linear-gradient(180deg,#4a7fe3,#2a5fc3)",
  btnPrimaryBorder: "#1a4fa3",
  btnPrimaryText: "#ffffff",
  btnSecondary: "linear-gradient(180deg,#f5f5f5,#e0e0e0)",
  btnSecondaryBorder: "#a0a0a0",
  btnSecondaryText: "#333333",
  tabActive: "linear-gradient(180deg,#4a7fe3,#2a5fc3)",
  tabActiveBorder: "#1a4fa3",
  tabActiveText: "#ffffff",
  tabInactive: "linear-gradient(180deg,#f5f5f5,#e0e0e0)",
  tabInactiveBorder: "#a0a0a0",
  tabInactiveText: "#333333",
  contentBg: "#f0f0f0",
  cardBg: "#ffffff",
  cardBorder: "#cccccc",
  fontFamily: "'Segoe UI', 'Tahoma', 'Arial', sans-serif",
  fontSize: "12px",
};

export const erpStyles = {
  toolbar: {
    background: ERP.toolbar,
    borderBottom: `1px solid ${ERP.toolbarBorder}`,
    padding: "4px 8px",
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontFamily: ERP.fontFamily,
    fontSize: "12px",
  } as React.CSSProperties,

  btn: (primary = false): React.CSSProperties => ({
    padding: "3px 12px",
    background: primary ? ERP.btnPrimary : ERP.btnSecondary,
    border: `1px solid ${primary ? ERP.btnPrimaryBorder : ERP.btnSecondaryBorder}`,
    borderRadius: 2,
    color: primary ? ERP.btnPrimaryText : ERP.btnSecondaryText,
    fontSize: "12px",
    fontFamily: ERP.fontFamily,
    cursor: "pointer",
    fontWeight: 600,
    whiteSpace: "nowrap" as const,
    display: "inline-flex" as const,
    alignItems: "center",
    gap: 4,
  }),

  statusChip: (status: string): React.CSSProperties => {
    const colors: Record<string, string> = {
      paid: "#007700", approved: "#007700", matched: "#007700", active: "#007700",
      pass: "#007700", passed: "#007700", allow: "#007700",
      pending: "#cc6600", draft: "#555555", monitor: "#cc6600", warning: "#cc6600",
      rejected: "#cc0000", cancelled: "#cc0000", failed: "#cc0000", inactive: "#555555",
      blocked: "#cc0000", block: "#cc0000", fail: "#cc0000",
      sent: "#2255cc", completed: "#007700", processing: "#2255cc",
      over_budget: "#cc0000", ended: "#555555", open: "#cc6600",
      resolved: "#007700", in_progress: "#2255cc",
      low: "#007700", medium: "#2255cc", high: "#cc6600", critical: "#cc0000",
      login: "#2255cc", logout: "#555555", create: "#007700",
      update: "#cc6600", delete: "#cc0000", view: "#555555",
    };
    const c = colors[status?.toLowerCase()] || "#555555";
    return {
      display: "inline-block",
      padding: "1px 7px",
      borderRadius: 10,
      fontSize: 10,
      fontWeight: 700,
      background: `${c}18`,
      color: c,
      border: `1px solid ${c}44`,
      textTransform: "uppercase" as const,
      letterSpacing: "0.04em",
      fontFamily: ERP.fontFamily,
    };
  },

  gridTh: {
    background: ERP.gridHeader,
    borderBottom: `2px solid ${ERP.gridHeaderBorder}`,
    borderRight: `1px solid ${ERP.gridBorder}`,
    padding: "5px 8px",
    fontSize: "11px",
    fontWeight: 700,
    color: ERP.gridHeaderText,
    fontFamily: ERP.fontFamily,
    textAlign: "left" as const,
    whiteSpace: "nowrap" as const,
    userSelect: "none" as const,
  } as React.CSSProperties,

  gridTd: {
    borderBottom: `1px solid ${ERP.gridBorder}`,
    borderRight: `1px solid ${ERP.gridBorder}`,
    padding: "4px 8px",
    fontSize: "12px",
    color: ERP.gridText,
    fontFamily: ERP.fontFamily,
    verticalAlign: "middle" as const,
  } as React.CSSProperties,

  inp: {
    padding: "3px 6px",
    border: "1px solid #aaaaaa",
    borderRadius: 1,
    fontSize: "12px",
    fontFamily: "'Segoe UI','Tahoma',sans-serif",
    outline: "none",
    background: "#ffffff",
    color: "#1a1a1a",
  } as React.CSSProperties,
};
