-- EL5 MediProcure v11.1.0 — AI Agent & Audit Log enhancements
-- Adds: user_id to audit_logs, sms_messages direction column,
--       ai_agent_events table, indexes for performance

-- 1. Ensure audit_logs has all needed columns
ALTER TABLE audit_logs
  ADD COLUMN IF NOT EXISTS user_id    uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS user_email text,
  ADD COLUMN IF NOT EXISTS ip_address text,
  ADD COLUMN IF NOT EXISTS module     text DEFAULT 'system',
  ADD COLUMN IF NOT EXISTS ref        text,
  ADD COLUMN IF NOT EXISTS amount     numeric(15,2);

-- 2. Index audit_logs for fast lookups
CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON audit_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_logs_action     ON audit_logs(action);
CREATE INDEX IF NOT EXISTS idx_audit_logs_module     ON audit_logs(module);

-- 3. Ensure sms_messages has direction column
ALTER TABLE sms_messages
  ADD COLUMN IF NOT EXISTS direction text DEFAULT 'outbound' CHECK (direction IN ('inbound','outbound')),
  ADD COLUMN IF NOT EXISTS module    text DEFAULT 'general',
  ADD COLUMN IF NOT EXISTS from_number text;

CREATE INDEX IF NOT EXISTS idx_sms_messages_module   ON sms_messages(module);
CREATE INDEX IF NOT EXISTS idx_sms_messages_channel  ON sms_messages(channel);
CREATE INDEX IF NOT EXISTS idx_sms_messages_sent_at  ON sms_messages(sent_at DESC);

-- 4. AI Agent events table
CREATE TABLE IF NOT EXISTS ai_agent_events (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  rule_id     text NOT NULL,
  trigger     text NOT NULL,
  ref         text,
  amount      numeric(15,2),
  department  text,
  channel     text,
  recipient   text,
  message     text,
  status      text DEFAULT 'pending' CHECK (status IN ('pending','sent','failed','skipped')),
  error       text,
  ai_model    text DEFAULT 'fallback',
  created_at  timestamptz DEFAULT now(),
  sent_at     timestamptz
);

CREATE INDEX IF NOT EXISTS idx_ai_agent_events_created ON ai_agent_events(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_agent_events_rule    ON ai_agent_events(rule_id);
CREATE INDEX IF NOT EXISTS idx_ai_agent_events_status  ON ai_agent_events(status);

-- 5. Enable Realtime on key tables for AI Agent auto-triggers
ALTER PUBLICATION supabase_realtime ADD TABLE requisitions;
ALTER PUBLICATION supabase_realtime ADD TABLE purchase_orders;
ALTER PUBLICATION supabase_realtime ADD TABLE ai_agent_events;

-- 6. RLS: audit_logs readable by admins
ALTER TABLE ai_agent_events ENABLE ROW LEVEL SECURITY;
CREATE POLICY "ai_agent_events_read" ON ai_agent_events
  FOR SELECT USING (true);
CREATE POLICY "ai_agent_events_insert" ON ai_agent_events
  FOR INSERT WITH CHECK (true);

-- 7. Function: log AI agent action with full context
CREATE OR REPLACE FUNCTION log_ai_agent_action(
  p_rule_id   text,
  p_trigger   text,
  p_ref       text DEFAULT NULL,
  p_amount    numeric DEFAULT NULL,
  p_channel   text DEFAULT 'sms',
  p_recipient text DEFAULT NULL,
  p_message   text DEFAULT NULL,
  p_status    text DEFAULT 'sent',
  p_model     text DEFAULT 'claude-haiku'
) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE v_id uuid;
BEGIN
  INSERT INTO ai_agent_events(rule_id,trigger,ref,amount,channel,recipient,message,status,ai_model,sent_at)
  VALUES (p_rule_id,p_trigger,p_ref,p_amount,p_channel,p_recipient,p_message,p_status,p_model,
          CASE WHEN p_status='sent' THEN now() ELSE NULL END)
  RETURNING id INTO v_id;

  INSERT INTO audit_logs(action,details,module,ref,amount,created_at)
  VALUES('ai_agent_'||p_rule_id,
         'AI Agent sent '||p_channel||' notification for '||COALESCE(p_ref,'unknown')||
         CASE WHEN p_amount IS NOT NULL THEN ' (KES '||p_amount::text||')' ELSE '' END,
         'ai_agent', p_ref, p_amount, now());

  RETURN v_id;
END;
$$;

COMMENT ON TABLE ai_agent_events IS 'AI Agent notification events — auto-generated by rules engine';
COMMENT ON FUNCTION log_ai_agent_action IS 'Logs AI agent send events to both ai_agent_events and audit_logs';
